/**
 * Self-hosts the site fonts (privacy: no request to Google at runtime).
 * Downloads the WOFF2 files for Plus Jakarta Sans + Space Grotesk
 * (SIL Open Font License) into public/fonts/ and writes
 * app/assets/css/fonts.css with matching @font-face rules.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Only the `latin` and `latin-ext` subsets are kept (English + Indonesian).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const fontDir = join(root, 'public', 'fonts')
mkdirSync(fontDir, { recursive: true })

const CSS_URL = 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap'
// A modern browser UA makes Google serve WOFF2
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'
const KEEP = new Set(['latin', 'latin-ext'])

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()
// Blocks look like: /* latin */ @font-face { ... }
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)]

const downloaded = new Map() // remote url -> local file
const out = ['/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */']

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue
  const family = block.match(/font-family:\s*'([^']+)'/)[1]
  const weight = block.match(/font-weight:\s*(\d+)/)[1]
  const url = block.match(/url\((https:[^)]+)\)/)[1]
  const range = block.match(/unicode-range:\s*([^;]+);/)[1]

  if (!downloaded.has(url)) {
    // Variable fonts: Google serves the same file for every weight → download once
    const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}-${downloaded.size}.woff2`
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
    writeFileSync(join(fontDir, file), buf)
    downloaded.set(url, file)
    console.log('✓', file, `${(buf.length / 1024).toFixed(1)} KB`)
  }

  out.push(`/* ${family} ${weight} ${subset} */
@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/${downloaded.get(url)}') format('woff2');
  unicode-range: ${range};
}`)
}

writeFileSync(join(root, 'app', 'assets', 'css', 'fonts.css'), `${out.join('\n')}\n`)
console.log(`fonts.css written (${out.length - 1} @font-face rules, ${downloaded.size} files)`)
